### ISSUE TITLE
Make pysgrid a "plugin" for iris/xray Software

### ISSUE THREAD

**Issue by ocefpaf** [sgrid/pysgrid#10]
Hi Andrew,

I have been following the development of pysgrid closely and I am interested in helping out.
I am specially interested into making pysgrid behave like a plugin module for Software like iris and xray.

PS: Also, I noticed that you are the sole commiter and merger of the repository, are you willing to try
a code review based approach for the PRs?

Best,

-Filipe

**Comment by ayan-usgs** [comment]
@ocefpaf,

I would greatly appreciate your help with SGRID. Could you elaborate on what you mean by "plugin"?

Also, I would be completely willing to do a code review approach for pull requests.

Regards,

Andrew

**Comment by ocefpaf** [comment]
> Could you elaborate on what you mean by "plugin"?

To be honest, not really sure on how to proceed right now.  I will study `pysgrid` code a little bit and check how to proceed.  The goal is to make `pysgrid` as friendly as possible to be used by the current CDMs we have out there.

> Also, I would be completely willing to do a code review approach for pull requests.

Great!  Just ping me on every PR you want me to review.

**Comment by ayan-usgs** [comment]
Cool. I see you've accept the admin invite that was sent. Awesome!

**Comment by ocefpaf** [comment]
(I am slowly catching up with my e-mails.  Conferences are fun, but the e-mail monster grows exponentially when you are in one ;-)
