### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [sgrid/pysgrid#103]
We just had a PR accepted with a version bump for 0.3.4

Could we make a release of that?

easier to run a conda-forge recipe if there is a release.

(I don't think I can do a PR fpr a release, can I?)

-CHB

**Comment by ChrisBarker-NOAA** [comment]
Now that I think about it -- we pushed a  0.3.4 build to our anaconda channel:

https://anaconda.org/NOAA-ORR-ERD/pysgrid

which is before the test fixes, etc that in master now.

So maybe best to bump the version to 0.3.5 for this "release".

Then we can point the conda-forge feedstock at it.

-CHB

**Comment by ayan-usgs** [comment]
I would be cool with a version 0.3.5 release. I'll try to get to it later today.

**Comment by ChrisBarker-NOAA** [comment]
Awesome, thanks.

-CHB

On Apr 19, 2017, at 5:41 AM, ayan-usgs <notifications@github.com> wrote:

I would be cool with a version 0.3.5 release. I'll try to get to it later
today.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/sgrid/pysgrid/issues/103#issuecomment-295255410>, or mute
the thread

**Comment by ChrisBarker-NOAA** [comment]
Done: thanks @ayan-usgs !
