### ISSUE TITLE
Identify cell centers and nodes in an SGRID

### ISSUE THREAD

**Issue by ayan-usgs** [sgrid/pysgrid#13]
@rsignell-usgs,

Do you happen to know of a way to reliably identify the grid cell centers and nodes in an SGRID? I'm currently using the long_name attribute, but I would prefer not to rely on an optional field.

**Comment by rsignell-usgs** [comment]
These are provided by the `face_coordinates` and `node_coordinates` attributes in the grid topology container variable, no?
```
   <variable name="grid" type="int">
        <attribute name="cf_role" value="grid_topology"/>
        <attribute name="topology_dimension" type="int" value="2"/>
        <attribute name="node_dimensions" value="xi_psi eta_psi"/>
        <attribute name="face_dimensions"
            value="xi_rho: xi_psi (padding: both) eta_rho: eta_psi (padding: both)"/>
        <attribute name="edge1_dimensions" value="xi_u: xi_psi eta_u: eta_psi (padding: both)"/>
        <attribute name="edge2_dimensions" value="xi_v: xi_psi (padding: both) eta_v: eta_psi"/>
        <attribute name="node_coordinates" value="lon_psi lat_psi"/>
        <attribute name="face_coordinates" value="lon_rho lat_rho"/>
        <attribute name="edge1_coordinates" value="lon_u lat_u"/>
        <attribute name="edge2_coordinates" value="lon_v lat_v"/>
        <attribute name="vertical_dimensions" value="s_rho: s_w (padding: none)"/>
    </variable>
```

https://github.com/ESIPFed/cf-dataset-curator/blob/master/datasets/mvco_roms/00_dir_roms.ncml#L109-L110

**Comment by ayan-usgs** [comment]
@rsignell-usgs,

I guess I was unclear in my original question. Yes, they are a part of the the SGRID convention and pysgrid does have them as attributes. 

However, face and edge coordinates are optional attributes. If they aren't present, I'd have to loop through the variables to find them and in that event, I'm wondering if there as more general way to find them then looking for the variables `lon_rho`, `lat_rho`, `lon_psi`, 'lat_psi' or 'MMAXZ', 'NMAXZ', or going through the 'long_name' attributes for each variable. Regardless of whether I search by variable or long_name, ROMS, Delft3D, and WRF have different conventions for identifying nodes. Hence, pysgrid would need to be able recognize each of those different conventions, which I feel is less than ideal. Is there a common way between ROMS, Delft3D, and WRF that nodes and centers and be identified?

**Comment by rsignell-usgs** [comment]
@ayan-usgs , okay, I see.  In the case where `node_coordinates` and `face_coordinates` are not explicitly provided, you should be able to read the required `location` attribute for the variable, and then look at variables in the `coordinates` attribute.   For  example, the `coordinates` of a `face` variable point to the `face_coordinates` variables.
