### ISSUE TITLE
Pysgrid should be be able to flexible enough to handle ROMS, Deltares, and WRF output 

### ISSUE THREAD

**Issue by ayan-usgs** [sgrid/pysgrid#16]
https://publicwiki.deltares.nl/display/NETCDF/Deltares+proposal+for+Staggered+Grid+data+model+(SGRID) provides examples for ROMS, Deltares, and WRF model output. The pysgrid package should be flexiable and "smart" enough to create an SGrid object from any of the three model outputs.

**Comment by rsignell-usgs** [comment]
@ayan-usgs , yes, it better.  That's the whole point, after all!  :smile_cat:

**Comment by ayan-usgs** [comment]
The current version of pysgrid seems to be doing this reasonably well.
