### ISSUE TITLE
SGRID compliant WRF model output

### ISSUE THREAD

**Issue by ayan-usgs** [sgrid/pysgrid#18]
I have been primarily using ROMS output for development so far and the documentation https://publicwiki.deltares.nl/display/NETCDF/Deltares+proposal+for+Staggered+Grid+data+model+(SGRID) for Delft3D and WRF output. Is there an SGRID compliant WRF output that can be used for development purposes? I would like to make sure pysgrid works with such a dataset.

A request for Delft3D data is made in issue #17.

**Comment by ayan-usgs** [comment]
@hrajagers or @rsignell-usgs,

Thoughts on where we can find an SGRID compliant WRF dataset?

**Comment by rsignell-usgs** [comment]
I don't have any SGRID-compliant WRF datasets either. 
@hrajagers, if you have one, please point us toward it.
Bert, if you don't have one, we *do* have plenty of WRF datasets around that we can fix up with NcML.

**Comment by ayan-usgs** [comment]
@hrajagers and @rsignell-usgs,

Thanks for the help!
