### ISSUE TITLE
rebase or make new forks for pysgrid

### ISSUE THREAD

**Issue by ayan-usgs** [sgrid/pysgrid#32]
@ocefpaf and @rsignell-usgs,

I noticed that the binary netCDF test files that were being used by pysgrid were causing the git repo to balloon size. I have modified the code to create the files when testing and delete them when testing is complete. I also needed to make changes to the Git history per the documentation at http://git-scm.com/book/en/v2/Git-Internals-Maintenance-and-Data-Recovery#Removing-Objects. I am _strongly recommending_ that you either rebase your forks or delete your old forks and fork from canonical master.

**Comment by ocefpaf** [comment]
@ayan-usgs take a look at: https://help.github.com/articles/working-with-large-files/

It might help.

**Comment by ayan-usgs** [comment]
@ocefpaf,

I'm not sure what I'm supposed to get out of that doc. I don't think it contains very much pertinent information.

**Comment by ocefpaf** [comment]
Sorry, I meant this on: https://www.google.com.br/search?q=github+large+file+support&oq=github+lar&aqs=chrome.0.69i59j69i57j0l4.2673j0j4&sourceid=chrome&es_sm=122&ie=UTF-8

**Comment by ocefpaf** [comment]
(My `v` key is failing and it is hard to know when copy-and-paste workd :stuck_out_tongue_winking_eye:)

**Comment by ayan-usgs** [comment]
@ocefpaf,

Thanks for the link. I still have no desire to have the test netCDF files under source control though. The package contains the necessary code the recreate them when needed. 

My intent was to allow facile cloning of the repository. I suspect a repo clone would still go out a get the binaries when using LFS, so I'm not particularly inclined to pursue at this point.

**Comment by ocefpaf** [comment]
It is up to you.  I like the idea of having the test data as well a test data generator script.  That way we can use them in examples, documentation, etc.  Some projects, before GitHub's lfs, have a separated repository for that.  See https://github.com/SciTools/iris-test-data for example.
