### ISSUE TITLE
SGrid Axes and Standard Name Requirement

### ISSUE THREAD

**Issue by ayan-usgs** [sgrid/pysgrid#35]
I was reviewing the thread at https://github.com/sgrid/sgrid/issues/1 where we discussed standard names for grid-aligned velocity components. While the discussion started with a suggestion to use the standard names sea_water_x_velocity and sea_water_y_velocity, the discussion eventually went to the direction of an axes attribute. From the discussion, I created a representative ROMS dataset using the axes attribute (https://gist.github.com/ayan-usgs/7d8de72ed8571790105e) as I understood it. While an axes attribute addresses variation in dimension order, in and of itself, axes would not allow one to discern the direction of the vector component. Are standard names still needed to define vector directions?

**Comment by ayan-usgs** [comment]
email message from @rsignell-usgs :

Yes, those standard_names would still be required.   Searching
standard_names looking for substring "velocity" is the only way to
identify velocity variables.

**Comment by ocefpaf** [comment]
@ayan-usgs and @rsignell-usgs I do not think that numerical models use `speed` and `direction`, but I have to search for those when identifying velocity in some observed datasets too.

**Comment by rsignell-usgs** [comment]
@ocefpaf, good point!

**Comment by rsignell-usgs** [comment]
But at least if we have speed and direction, it won't be on a staggered grid!
