### ISSUE TITLE
Grid Angles

### ISSUE THREAD

**Issue by ayan-usgs** [sgrid/pysgrid#36]
ROMS models have an angles variable, but that doesn't seem to be the case with WRF and delft3d models. Is that a correct assessment? If it is, would it be necessary to derive angles from other variables within the dataset?

**Comment by ayan-usgs** [comment]
@rsignell-usgs,

What are your thoughts regarding this?

Thanks!

**Comment by ayan-usgs** [comment]
During a phone call @rsignell-usgs mentioned that the angle of the grid would have to be calculated from latitude and longitude values.

**Comment by ayan-usgs** [comment]
@kwilcox,

Rich mentioned that you already have a function to do this. Would you be willing to share it with me?

**Comment by kwilcox** [comment]
Sorry, I don't have a function that does the calculation from lat and lon values.. I've only ever needed to do this with ROMS and have used the `angle` variable that already exists.

**Comment by ayan-usgs** [comment]
@kwilcox,

Thanks for letting me know.

**Comment by rsignell-usgs** [comment]
Here is what our Matlab code had:
```
x=ncmex('varget',ncid,'lon_rho',[0 0],[-1 -1]);
y=ncmex('varget',ncid,'lat_rho',[0 0],[-1 -1]);

x_rho = x';
y_rho = y';


[eta_rho_length, xi_rho_length] = size(x_rho);
eta_u_length = eta_rho_length;
eta_v_length = eta_rho_length-1;
xi_u_length = xi_rho_length-1;
xi_v_length = xi_rho_length;
eta_psi_length = eta_rho_length-1;
xi_psi_length = xi_rho_length-1;

% construct the grids at the psi points.
xtemp = (x_rho(:,1:(xi_rho_length-1)) + x_rho(:,2:xi_rho_length))/2;
x = (xtemp(1:(eta_rho_length-1),:)  + xtemp(2:eta_rho_length,:))/2;
ytemp = (y_rho(:,1:(xi_rho_length-1)) + y_rho(:,2:xi_rho_length))/2;
y = (ytemp(1:(eta_rho_length-1),:)  + ytemp(2:eta_rho_length,:))/2;

x = x.'; y = y.';
[r,c] = size(x);
j = [2:c-1];
for i = 2:r-1
   angle(i,j) = atan2(y(i+1,j)-y(i-1,j), x(i+1,j)-x(i-1,j));
end
```

**Comment by rsignell-usgs** [comment]
But I see that this matlab code was using lon, lat as x,y, which is not correct.  We should be using something like

```
import seawater as sw
dist, angle = sw.dist(lat, lon, units='km')
```
as demonstrated here:
http://nbviewer.ipython.org/gist/ocefpaf/9255e5cea03f7705a5fe

**Comment by rsignell-usgs** [comment]
@ayan-usgs , can you use this to make a more general SGRID version?
You could use the ROMS data as a check to make sure you get back something close to the known angle (it won't be exact, but should be very close).

**Comment by ayan-usgs** [comment]
@rsignell-usgs,

Thanks for the matlab example. I actually had a preliminary Python version of it to do the angle calculation soon after I say Kyle's message. :smile:  Still working on the kinks though.

**Comment by rsignell-usgs** [comment]
Yeah, this stuff is tricky.  Angles and indices together.  Scary!  :fearful:

**Comment by ayan-usgs** [comment]
I've added a pretty general way of calculating angles in pysgrid.

**Comment by rsignell-usgs** [comment]
Uh, where?  Was there a Pull Request?

**Comment by ayan-usgs** [comment]
@rsignell-usgs,

It was this commit: https://github.com/sgrid/pysgrid/commit/a91c9994cca5cc344a6f8aa7abf839f798a225d8.

**Comment by ocefpaf** [comment]
@ayan-usgs you had 14 commits in that PR (#38), changing 9 files ranging from tests, bugfixes, spelling errors and the actual `calculate angles` implementation.  That makes it very hard for others to follow and contribute to pysgrid development!

I do recommend to commit as often as you do, but before sending the PR try re-basing them to a few meaningful commits.  Also try to send smaller PRs :wink:
