### ISSUE TITLE
handling of time variables in pysgrid

### ISSUE THREAD

**Issue by ayan-usgs** [sgrid/pysgrid#41]
This issue was spawned from a discussion on PR #40.

Should pysgrid handle time variables? It currently makes an effort to, but it's becoming apparent that it's not necessary for an staggered grid topology. 

If there's value in doing so, we should, but it's not immediately obvious if there is. If there is value here, it should also be "smart" enough to deal with multiple variables with `standard_name=time`.

**Comment by rsignell-usgs** [comment]
I can't think of any reason for pysgrid to handle time.

**Comment by ayan-usgs** [comment]
Alright. I'm going to remove it/

**Comment by ocefpaf** [comment]
:+1:

**Comment by kwilcox** [comment]
:+1: A similar decision was made for pyugrid awhile back... it doesn't manage anything but the specific UGRID things.
