### ISSUE TITLE
Avoid full slices

### ISSUE THREAD

**Issue by ocefpaf** [sgrid/pysgrid#69]
pysgrid code perform full data slices in some places like:

https://github.com/sgrid/pysgrid/blob/master/pysgrid/sgrid.py#L497-L532

That can be memory expensive and/or slow when the data origin in remote.

Options:
 1. Pass along the netCDF4-python variable instead of the slice.  Maybe with little to no modification all the 2D processing will just work.
 2. Make them a lazy array using either dask or biggus.

Option 2 adds a dependency and the smart thing to do would be to implement 1 having 2 as an optional behavior  when the dependency is available.  The advantages of 2 over 1 are: (a) to be able to load data that is bigger than memory; (b) avoid worrying about index logic when performing lazy computations.

**Comment by rsignell-usgs** [comment]
I wouldn't worry about the dependency and just go for dask (didn't the biggus guys say they were going to replace biggus with dask eventually?)

**Comment by ocefpaf** [comment]
There is a lot to do!  This PR just avoid loading all the data in `get_cell_center_lat_lon`.  However, `pair_arrays` will do that later :unamused: 

We need either to make them lazy as soon as possible and adapt the code to use only lazy arrays, or to implement a custom `__gettiem__`.

**Comment by ocefpaf** [comment]
@ayan-usgs is the rational behind pairing the arrays?  I know that `pyugrid` does the same, but I find that a violation of the data model.  The netCDF file is not paired so why should we?

**Comment by rsignell-usgs** [comment]
If this came from `pyugrid`, perhaps @ChrisBarker-NOAA remembers the rationale...

**Comment by ocefpaf** [comment]
I asked him that at SciPy, but I was unconvinced :wink:

I don't want to split hairs. And I do understand that it more compact to hold lon, lat into 1 variable.
However, we should strive for compatibility with the rest of the world.

Also, what is the point of doing this here to later on do this,
```python
lon_data = grid_cell_centers[..., 0][sg_lon.center_slicing]
lat_data = grid_cell_centers[..., 1][sg_lat.center_slicing]
```

when plotting?

**Comment by rsignell-usgs** [comment]
I agree.   I find that confusing.  I have to then remember the order too.

**Comment by ocefpaf** [comment]
Maybe we just found another case for APIRUS :wink: 
@rsignell-usgs can you open an issue there for us please?

**Comment by ayan-usgs** [comment]
@ocefpaf,

There wasn't a strong motivating factor to do that other than to have some consistency with `pyugrid` at the time the code was written. I have no objection to changing that so that lat and lon are separate.

**Comment by ocefpaf** [comment]
Great @ayan-usgs!  Let's coordinate to get this changed in both libraries then.

**Comment by ChrisBarker-NOAA** [comment]
BTW -- what  are these ``pair_arrays`` you speak of?

**Comment by ocefpaf** [comment]
In `pysgrid` it is here: https://github.com/sgrid/pysgrid/blob/4f0087143650e45c95a63be0363d2c84bd2210b0/pysgrid/utils.py#L19-L39

**Comment by ChrisBarker-NOAA** [comment]
I see -- so this is essentially taking what may be two MxN arrays of, say, lat and lon, and making a MxNx2 array of lat-lon pairs.

OK -- I can see how that might start to feel a bit more ugly when you add extra dimensions...with 1-d it seems so natural.

Also -- a quick grep through the py_ugrid code does find a lot of "nodes[:,0]" etc....

But if you spilt lat and long up, you now could get them out of sync -- and do we make the rest of the API keep them apart as well, like the ``locate_nodes(self, points)`` method, etc.

Does anyone really like dealing with an individual point as a two distinct variables?

But the main driver here may be the lazy-loading thing -- if you want to lazy load, it's a lot easier to follow the data model of what you are loading from...

-CHB

**Comment by ocefpaf** [comment]
> Does anyone really like dealing with an individual point as a two distinct variables?

I do.  Also, `xray`, `iris`, virtually all plotting packages, and the CF-models is that way.

> But the main driver here may be the lazy-loading thing.

Not really.  That would be a bonus for this change.  We could create a "lazy_paired" array.

> it's a lot easier to follow the data model of what you are loading from

The motivation is not to make it easy, but consistent with the model we are loading from.

We have to remember that people will mix grid-like objects with data loaded with other packages (raw netCDF4-python, xray, iris, etc).  IMO it is important to be consistent.  Do we really want to see people plotting like?

```python
ax0.plot(nodes[:,0], nodes[:,1], temp)
ax1.plot(ds.lon, ds.lat, ds.temp)
```

**Comment by ChrisBarker-NOAA** [comment]
> We could create a "lazy_paired" array.

We could, and would, I think gain the API, but not the performance advantages -- one of the point sis to keep lon and lat close to each-other in memory...

Do we really want to see people plotting like?

```
ax0.plot(nodes[:,0], nodes[:,1], temp)
ax1.plot(ds.lon, ds.lat, ds.temp)
```
well, first,  I'm proposing:

```
ax0.plot(nodes.lon, nodes.lat, temp)
```
but even more to the point, the goal is is a better API that doesn't make you know about the grid, so it's really something like

```
temp.plot(ax0)
```

but anyway -- what'st he new AP goign to look like:

```
ax0.plot(nodes_lon, node_lat, temp) ?
```
there are quite a few lon-lat paris in the UGRID API, so this gets a bit painful, but sure, maybe better to be consistent with everyone else.

Note -- I think I still might want a lazy_pair, so we can have a UGrid.nodes property -- even if it is stored internally as UGrid.nodes_lon and UGrid.node_lat

**Comment by ocefpaf** [comment]
Done in #72
