### ISSUE TITLE
Getting rid of the Metaclass and the 3D class

### ISSUE THREAD

**Issue by ocefpaf** [sgrid/pysgrid#71]
@ayan-usgs I know that this is a drastic change, but I believe the SGRID conventions should not cover 3D staggered grids.  And, if that is revised to do so, we can simplify the code a lot and lower the entry barrier for newcomers.

**Comment by ayan-usgs** [comment]
@ocefpaf,

That's fine. I was intending to remove it. There aren't any use cases for 3D grids. The only reason it's still there was because I never got a response from @hrajagers whether he was okay with dropping 3D  grid from the conventions.

**Comment by ocefpaf** [comment]
Awesome :smile:
