### ISSUE TITLE
Huge .pack file dominating repository

### ISSUE THREAD

**Issue by jay-hennen** [sgrid/pysgrid#75]
If you want to clone/fork this repository there's currently a giant .pack file residing in .git/objects/pack/ that is over 90MB in size. This makes up over 99% of the repository's size.

If netCDF files were on the repository and subsequently removed, it might be worth purging them from the history to eliminate some of this .pack file's girth

**Comment by ocefpaf** [comment]
Hi @jay-hennen that is indeed a problem.  Thanks for pointing that out.  I will see if I can filter that file out of the history.  Let's leave this issue opened until than.

**Comment by ocefpaf** [comment]
I purged `*.nc` files in master with:

```shell
git filter-branch --tag-name-filter cat --index-filter 'git rm -r --cached --ignore-unmatch *.nc' --prune-empty -f -- --all
rm -rf .git/refs/original/
git reflog expire --expire=now --all
git gc --aggressive --prune=now
git push origin --force --all
git push origin --force --tags
```

Now you can either start a new fork or do:

```shell
cd MY_LOCAL_GIT_REPO
git fetch origin
git rebase
git reflog expire --expire=now --all
git gc --aggressive --prune=now
```

PS: If I did it right and if I got how garbage collection works in servers it might take a while until the space is freed in GitHub.

Reference: http://blog.ostermiller.org/git-remove-from-history

**Comment by jay-hennen** [comment]
I'm not sure it's fixed. I forked the repo and it still wants me to download 90MB when I clone it. Or hasn't GitHub cleaned it's end up yet?

**Comment by ayan-usgs** [comment]
bfg might be a good tool to use for this. https://rtyley.github.io/bfg-repo-cleaner/

I've used it a few times and have been pleased with it.

**Comment by ocefpaf** [comment]
I don't believe it is a tool problem.  I am contacting GitHub help to understand why the files are still there.

**Comment by ocefpaf** [comment]
I wrote GitHub support and I think it got solved. 

> Hi Filipe,
>
> Sorry for the delay here!
>
> It looks like you did the filter branch correctly. I just GCed your repo on our end, can you check if you're still seeing this issue?
>
> Thanks,
> Rachel

**Comment by jay-hennen** [comment]
This is still not solved. The files are gone from the commit history, but they are still in the .pack file. If I try to clone it still wants to download 95MB of stuff.

http://stackoverflow.com/questions/1904860/how-to-remove-unreferenced-blobs-from-my-git-repo/14728706#14728706

Running the script in that page fixed it immediately on my local repo. The pack size has shrunk to 804kb. However, I don't think there's any way to remove these ureferenced blobs from Github's git repository without their help.
