### ISSUE TITLE
netcdf version

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [sgrid/pysgrid#86]
Does it really need this specific version of netcdf?

netCDF4 >=1.2.0,<1.2.2

1.2.2 is the current version in conda....

**Comment by ayan-usgs** [comment]
Yes. There is a bug in 1.2.2. That particular requirement will be revisited with subsequent versions of netCDF4.

**Comment by ocefpaf** [comment]
See https://github.com/sgrid/pysgrid/pull/81

**Comment by ChrisBarker-NOAA** [comment]
Got it -- indeed, I did get some segfaults the first time I tried running the tests (in our fork, I thought was a problem with our fork!)
