### ISSUE TITLE
Coding Style Guide

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [sgrid/pysgrid#88]
It would be nice to have a style guide (and to share it with pysgrid).

THe Iris developers guide is a good start:

 iris developers guide. 

http://scitools.org.uk/iris/docs/v1.9.2/developers_guide/index.html

But it's a bit short on style. As far as I can tell, they recommend PEP8 for code, and  PEP 0257 for docstrings, but we could use some expansion on those:

When to use single vs double quotes

How to specify parameters to functions.

How to do line continuations.

(I, at least have strong opinions about some of these, so I guess I"ll start:

### single vs double quotes:

PEP8 does not make a recomendation -- I don't care, if someone else does, then can fill this in :-)

### Specifying parameters to functions in docstrings

I think we should use either the "raw" sphinx approach:

:param name: the value you want to pass in
:type name: the type required for name

Or adopt the numpy extensions -- they are nicer, but require an extra plug-in...

https://pypi.python.org/pypi/numpydoc

### line continuations

long lines need to get split, but there are multiple ways to do it.

Use un-closed brackets whenever possible to support continuation.

If a function definition or function call has too many parmaeters to all fit on one line, then put each on on it's own line. i.e.

```
    def __init__(self,
                 node_lon=None,
                 node_lat=None,
                 center_lon=None,
                 center_lat=None,
                 edges=None,
                 node_padding=None,
                 edge1_padding=None,
                 edge2_padding=None,
                 grid_topology_var=None,
                 variables=None,
                 grid_variables=None,
                 dimensions=None,
                 node_dimensions=None,
                 node_coordinates=None,
                 edge1_coordinates=None,
                 edge2_coordinates=None,
                 angles=None,
                 )
```
not:

```
    def __init__(self, node_lon=None, node_lat=None, center_lon=None,
                 center_lat=None, edges=None, node_padding=None,
                 edge1_padding=None, edge2_padding=None, grid_topology_var=None,
                 variables=None, grid_variables=None, dimensions=None, node_dimensions=None, node_coordinates=None, edge1_coordinates=None,
                 edge2_coordinates=None, angles=None)
 
Also, for literals for arrays of points that dont fit on one line (or maybe even if they do, alighing them logically is nice:

``
the_points = [ (x1, y1),
               (x2, y2),
               (x3, y3),
               (x4, y4),
               (x5, y5),
               (x6, y6),
              ]
```

Also, putting the closing bracket on the next line and leaving a trailing comma, even after the last item, make it a lot easier to comment out and add in new items.

Maybe this shodo be a PR to the APIRUS project, and we can point to that?

**Comment by ocefpaf** [comment]
> It would be nice to have a style guide (and to share it with pysgrid).

pyugrid?

**Comment by ChrisBarker-NOAA** [comment]
yup -- I forgot what project I was posting to :-)

Which is why these should all be in one project, or at least one organization -- but that can wait.

-CHB

**Comment by ChrisBarker-NOAA** [comment]
I put a start of one in the APIRUS project:

https://github.com/ioos/APIRUS/blob/master/style_guide.rst

we can start pointing to that for this project.
