### ISSUE TITLE
BSD type

### ISSUE THREAD

**Issue by ocefpaf** [sgrid/pysgrid#90]
@ayan-usgs what type of BSD license do think is fitting here 2 or 3-Clauses? (Can you add a LICENSE.txt file?)

**Comment by ayan-usgs** [comment]
Sure. I'll add a license.

**Comment by ocefpaf** [comment]
Thanks @ayan-usgs.

PS: Do you want to be a maintainer of the conda-forge package? If so just send a PR with your GitHub handle [here](https://github.com/conda-forge/pysgrid-feedstock/blob/master/recipe/meta.yaml#L34-L36).

**Comment by ocefpaf** [comment]
Done in #91
