### ISSUE TITLE
padding_slices ?

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [sgrid/pysgrid#95]
I'm confused by the class attribute `padding_slices` -- it's in the `SGrid` class, but is only used in:

`pysgrid/utils/determine_variable_slicing`

honestly, I'm confused about that this is really useful for, but it strikes me that either that utuil function should be in `SGrid`, or `padding_slices` should be defined in `utils`.

**Comment by ayan-usgs** [comment]
In retrospect, I think `padding_slices` should be defined in `utils`.

The SGRID convention draft https://publicwiki.deltares.nl/pages/viewpage.action?pageId=108953628 recognizes four relationships between face/edge and node dimensions. The `padding_slices` defines how variables should be subsetted based on those relationships. This is particularly useful when averaging variables defined on edges to cell centers.

**Comment by ChrisBarker-NOAA** [comment]
OK -- let's move it there.

Though I'm a bit confused -- I'll need to look at the spec again more carefully -- but it seems that the SGrid object had better know what the relationships are between the dimensions -- or is that captured somewhere other than padding-slices?

**Comment by ChrisBarker-NOAA** [comment]
BTW, it seems the gitHub version is now the "official" one:

https://github.com/sgrid/sgrid/blob/gh-pages/index.md

**Comment by ayan-usgs** [comment]
> but it seems that the SGrid object had better know what the relationships are between the dimensions -- or is that captured somewhere other than padding-slices?

The SGrid object does superficially keep track on what it's padding is; it keeps track of the attribute value (e.g. high, low, both, etc). The `SGridVariable` object does much more of the heavy lifting in terms of actually taking advantage of the attribute; the variable object has a couple `*_slicing` attributes derived from the padding that specifies how the variable is affected by the padding. It gets a bit complicated depending on where the variable is defined and what one is trying to do. 

If you have thoughts for improvements and simplifying some of this, feel free to suggest. :smile:

**Comment by ChrisBarker-NOAA** [comment]
OK, that makes sense. What I think we need to do now is come up with a standard API for `SGridVariable` objects and `UVar` objects (and a similar naming scheme :-) -- then we can see where this should all fall out.

Not sure if/when I'll get a chance to actually do that, so closing this for now.
